### PR TITLE
add support for openbay-dump-db

### PR DESCRIPTION
**Pull request by oXis**
I added the support for openbay dump. It's working on my computer. I also added "Size" into the database. It's a little bit quick and dirty, it will be good to add column name into the csv then parse it. Or it may be useless if the structure is always the same.

Just an idea, reject the request if you already know a better way to do that :)

### CODE REVIEW

**Comment by Stephen304** [comment]
I think this is great! Is this the open bay dump that you download via bittorrent from http://openbay.isohunt.to/? I was thinking about adding support, but I hadn't seen the dump and I didn't think it would be a csv, so similar to the other dumps.

I'll want to do a bit of testing later today to make sure that empty fields don't add much to the database size, then I'll merge it. If it does add too much size to the database, I'll probably drop the size for now.

Either way it's great to have this, thanks for the awesome work!

**Comment by oXis** [comment]
Those empty fields are for "Details" and "Download" (I think you already know that -_-), but there is no such things in the openbay dump. You are using magnet, and that a great idea, but I think you can drop the "Download" column. It's very easy to add column to your database (NoSQL?), so maybe add Seed/Leech, ... in future update.

The dump is from here -> https://github.com/isohuntto/openbay-db-dump
You can also find a huge .sql dump (50Go, about 23M torrents) in the issues section.

**Comment by Stephen304** [comment]
Ah, I meant if there is size and it isn't populated so it's 0. The KAT and Demonoid have 2 links for details and download. The download url points to a torrent file cache that gives a .torrent from the magnet link.

Now that I think about it, Download is completely unnecessary, and that should more than make up for adding a size field.

Good work! This will be merged later (when I get off work in 5 hours)

**Comment by Stephen304** [comment]
Does it make sense to set size as -1 if there is no size? I've been following a similar scheme with seeders and leechers to differentiate between torrents that havent been scraped yet and torrents that actually have 0 seeders/leechers, so I might do the same for size

**Comment by oXis** [comment]
I'll change the 0 to -1. I can remove the Download field too if you want.

**Comment by Stephen304** [comment]
Actually I think 0 is fine. For seeders 0 is a valid number so using -1 makes sense, but for size, 0 doesnt make sense as a valid size so i think it works as a placeholder.

**Pull request merged**
